#page title
page_title                                : Never Forget Reminder                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# Multilingual Configuration
languages                                 : ["zh", "en"]
default_language                          : "zh"
language_names                            :
  zh                                      : "中文"
  en                                      : "English"

# SEO Configuration
url                                       : "https://reminder.iofree.xyz"  # Update with your actual domain
baseurl                                   : ""

# SEO Meta Tags
title                                     : "不忘提醒 - Never Forget Reminder"
description                               : "功能强大的iOS提醒应用，支持循环提醒、倒计时、时间线提醒。Powerful iOS reminder app with recurring reminders, countdown timers, and timeline reminders."
keywords                                  : "提醒,reminder,iOS,app,循环提醒,倒计时,时间线,recurring,countdown,timeline,productivity,生产力"
author                                    : "Allen"

# Social Media
twitter:
  username                                : Allen_Xuxu
  card                                    : summary_large_image

# Facebook/Open Graph
facebook:
  app_id                                  : # Add your Facebook App ID if you have one

# Google Analytics (add your tracking ID)
google_analytics                          : # Add your GA tracking ID

# Search Engine Verification
google_site_verification                  : # Add your verification code
bing_site_verification                    : # Add your Bing verification code
baidu_site_verification                   : # Add your Baidu verification code (for Chinese SEO)

# Additional SEO settings
locale                                    : "zh_CN"
timezone                                  : "Asia/Shanghai"

# Multilingual App Store Links
appstore_links                            :
  zh                                      : https://apps.apple.com/cn/app/%E4%B8%8D%E5%BF%98%E6%8F%90%E9%86%92-%E9%87%8D%E5%A4%8D%E6%8F%90%E9%86%92-%E6%9C%AA%E6%9D%A5%E6%8F%90%E9%86%92-%E5%AE%9A%E6%97%B6%E5%99%A8/id1600249479?uo=4
  en                                      : https://apps.apple.com/us/app/never-forget-reminder-repeat-future-timer/id1600249479?uo=4

# Multilingual APK Download Links (optional - only shows if configured)
apk_links                                 :
  zh                                      :          # Enter APK download URL for Chinese users
  en                                      :          # Enter APK download URL for English users

# Multilingual App Info
app_info                                  :
  zh                                      :
    name                                  : 不忘提醒 - 重复提醒、未来提醒、定时器
    description                           : 帮助你不忘记任何一件小事
    price                                 : 免费
  en                                      :
    name                                  : Never Forget Reminder - Repeat, Future, Timer
    description                           : Help you never forget anything
    price                                 : Free

# App Info
ios_app_id                                : 1600249479                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : cn                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/cn/app/%E4%B8%8D%E5%BF%98%E6%8F%90%E9%86%92-%E9%87%8D%E5%A4%8D%E6%8F%90%E9%86%92-%E6%9C%AA%E6%9D%A5%E6%8F%90%E9%86%92-%E5%AE%9A%E6%97%B6%E5%99%A8/id1600249479?uo=4                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
apk_link                                  :                                           # Enter APK download URL (fallback if multilingual links not set).
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/logo.jpeg                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Never Forget Reminder - Repeat, Future, Timer           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Help you never forget anything

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Allen
your_link                                 :
your_city                                 :
email_address                             : admin@iofree.xyz
facebook_username                         :
instagram_username                        :
twitter_username                          : Allen_Xuxu
github_username                           :
youtube_username                          :

#picture_CDN                               : https://cdn.jsdelivr.net/gh/iofree/reminder-site          # 图片 cdn 前缀


# Feature List - Now using _data/features/ for multilingual support
# Legacy features configuration removed - features are now loaded from:
# - _data/features/zh.yml (Chinese)
# - _data/features/en.yml (English)

img  : # 展示 feature 下面的截图
  - url                                  : assets/img/1.png
  - url                                  : assets/img/2.png
  - url                                  : assets/img/3.png
  - url                                  : assets/img/4.png
  - url                                  : assets/img/5.png
  - url                                  : assets/img/6.png
  - url                                  : assets/img/7.png

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

# Performance optimizations
incremental: true
profile: true
strict_front_matter: true

# Plugin configuration
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Build settings
future: false
show_drafts: false
unpublished: false

# Liquid options
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Compression
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
