
# Page Configuration
page_title                                : Never Forget Reminder

# Multilingual Configuration
languages                                 : ["zh", "en"]
default_language                          : "zh"
language_names                            :
  zh                                      : "中文"
  en                                      : "English"

# SEO Configuration
url                                       : "https://reminder.iofree.xyz"
baseurl                                   : ""
title                                     : "不忘提醒 - Never Forget Reminder"
description                               : "功能强大的iOS提醒应用，支持循环提醒、倒计时、时间线提醒。Powerful iOS reminder app with recurring reminders, countdown timers, and timeline reminders."
keywords                                  : "提醒,reminder,iOS,app,循环提醒,倒计时,时间线,recurring,countdown,timeline,productivity,生产力"
author                                    : "Allen"
locale                                    : "zh_CN"
timezone                                  : "Asia/Shanghai"


# Analytics & Verification
google_analytics                          :
google_site_verification                  :
bing_site_verification                    :
baidu_site_verification                   :

# App Store Links
appstore_links                            :
  zh                                      : https://apps.apple.com/cn/app/id1600249479?uo=4
  en                                      : https://apps.apple.com/us/app/id1600249479?uo=4
# Multilingual APK Download Links (optional - only shows if configured)
apk_links                                 :
  zh                                      :      
  en                                      : 

playstore_link                            :

# Multilingual App Info
app_info                                  :
  zh                                      :
    name                                  : 不忘提醒
    description                           : |
                                            帮助你不忘记任何一件小事！
                                            重复提醒、未来提醒、定时器、日历视图。
    price                                 : 免费
  en                                      :
    name                                  : Never Forget Reminder
    description                           : |
                                            Help you never forget anything!
                                            Repeat, Future, Timer, Calendar.
    price                                 : Free

# App Configuration
ios_app_id                                : 1600249479
ios_app_country                           : cn
app_icon                                  : assets/logo.jpeg
enable_smart_app_banner                   : true


# Information About Yourself
your_name                                 : Allen
your_link                                 :
your_city                                 :
email_address                             : admin@iofree.xyz
facebook_username                         :
instagram_username                        :
twitter_username                          : Allen_Xuxu
github_username                           :
youtube_username                          :

#picture_CDN                               : https://cdn.jsdelivr.net/gh/iofree/reminder-site          # 图片 cdn 前缀

# Screenshot Images
img                                       :
  - url                                   : assets/img/1.png
  - url                                   : assets/img/2.png
  - url                                   : assets/img/3.png
  - url                                   : assets/img/4.png
  - url                                   : assets/img/5.png
  - url                                   : assets/img/6.png
  - url                                   : assets/img/7.png

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black

body_background_color                     : "#ffffff"
link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

# Plugin configuration
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Build settings
future: false
show_drafts: false
unpublished: false

# Liquid options
liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

